
name: CI


on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
    - uses: max/secret-scan@master
    - uses: actions/checkout@v1
    - name: gitleaks-action
      uses: zricethezav/gitleaks-action@master

      
      

